services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_URL
        fromDatabase:
          name: strapi_postgres_chatapp
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: DATABASE_POOL_MIN
        value: 2
      - key: DATABASE_POOL_MAX
        value: 10
      - key: DATABASE_CONNECTION_TIMEOUT
        value: 60000
      - key: DATABASE_CREATE_TIMEOUT
        value: 30000
      - key: DATABASE_IDLE_TIMEOUT
        value: 30000

databases:
  - name: strapi_postgres
    plan: free
