services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health

databases:
  - name: strapi_postgres
    plan: free
